/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.lab510.cryptodac;

import org.lab510.cryptodac.config.ConfigParser;
import org.lab510.cryptodac.config.ConfigProcessor;
import org.lab510.cryptodac.config.Configuration;
import org.lab510.cryptodac.dac.DAC;
import org.lab510.cryptodac.dac.DACRunnner;
import org.lab510.cryptodac.dac.PREDAC;
import org.lab510.cryptodac.dac.PublicKeyDAC;

public class App {

    public static void main(String[] args) {
        String configFile = args[0] + ".properties";
        Configuration config = null;

        try {
            config = new ConfigParser().parse(configFile);
            new ConfigProcessor().process(config);
        } catch (Exception e) {
            System.out.println(String.format("cannot process config file %s", configFile));
        }

        // DAC dac = new PREDAC(config);
        DAC dac = new PublicKeyDAC(config);
        new DACRunnner(dac).run();
    }
}
