/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.lab510.cryptodac;

import java.io.IOException;
import org.lab510.cryptodac.config.ConfigParser;
import org.lab510.cryptodac.config.ConfigProcessor;
import org.lab510.cryptodac.config.Configuration;
import org.lab510.cryptodac.dac.DAC;
import org.lab510.cryptodac.dac.DACRunnner;
import org.lab510.cryptodac.dac.PREDAC;
import org.lab510.cryptodac.dac.PublicKeyDAC;
import org.lab510.cryptodac.error.Error;

public class App {

    private String[] args;
    DAC dac = null;

    public App(String[] args) {
        this.args = args;
    }

    void checkArgs() throws IOException {
        if (args.length < 2)
            throw new Error(
                    "Use as gradle run --args [domino, emea, firewall1, firewall2, healthcare, university] [PRE, PK]");

        String configFile = args[0] + ".properties";
        var config = new ConfigParser().parse(configFile);
        new ConfigProcessor().process(config);

        if (args[1].equals("PRE"))
            dac = new PREDAC(config);
        else if (args[1].equals("PK"))
            dac = new PublicKeyDAC(config);
        else
            throw new Error("please give the type as PRE or PK");
    }

    void run() {
        new DACRunnner(dac).run();
    }

    public static void main(String[] args) throws IOException {
        App app = new App(args);
        app.checkArgs();
        app.run();
    }
}
